Expose dbs as support modules to external IOCs
gustavosr8/ipmiComm pull request #2
Opened 2024-06-05 17:40 UTC by gustavosr8

Since the created dbs implements an accessible way of using the support driver, it would be helpful to expose them as support modules.

2024-06-05 17:54 UTC, ericonr commented
Suggested commit message (please wrap it):

```
Install general templates.

These templates can be used by external IOCs to compose their own specific
devices without having to copy the files into their own repository. Installing them
is the best way to make them accessible for those users. 
```

2024-06-05 18:41 UTC, henriquesimoes requested changes

2024-06-05 18:41 UTC, henriquesimoes commented on Db/Makefile
> +#  Abs:
I know it hurts, but I'd let this out of this patch.

2024-06-05 18:41 UTC, henriquesimoes commented on Db/Makefile
> +# Templates to be loaded per device
This one too.

2024-06-06 12:03 UTC, ericonr approved these changes

2024-06-10 17:56 UTC, henriquesimoes approved these changes

2024-06-11 12:36 UTC, merged